[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit ILI9341 @ ^1.5.12
    adafruit/Adafruit MLX90614 Library @ ^2.1.3
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    adafruit/Adafruit_VL53L0X @ ^1.2.4
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.2
    adafruit/Adafruit INA219 @ ^1.2.1
    lvgl/lvgl @ ^8.3.9
    bodmer/TFT_eSPI @ ^2.5.31

[env:Main]
board_build.partitions = huge_app.csv

build_src_filter =
    -<*.cpp>
    +<main.cpp>
    +<boot_screen.cpp>
    +<ecg_ai_bridge.cpp>
    +<ina219_sensor_module.cpp>
    +<lcd_sensor_runtime.cpp>
    +<lcd_ui_presenter.cpp>
    +<ui.cpp>
    +<ui_datacollector.cpp>
    +<max30102_sensor_module.cpp>
    +<mlx90614_sensor_module.cpp>
    +<ad8232_sensor_module.cpp>
    +<wifi_config_manager.cpp>
    +<ad8232.cpp>
    +<icons/*.c>

build_flags =
    -D TARGET_ESP32S3_V2=1

    ; LCD ILI9341 SPI
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=-1
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=8
    -D TFT_BL=7
    -D SPI_FREQUENCY=27000000

    ; LVGL
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_COMP_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I include

    ; ESP32-S3 runtime
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
    -D CORE_DEBUG_LEVEL=0