/*******************************************************************************
 * Custom Icons Header - Auto-generated by icon_generator.py
 * DO NOT EDIT MANUALLY - Use icon_generator.py to add new icons
 ******************************************************************************/

#ifndef CUSTOM_ICONS_H
#define CUSTOM_ICONS_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

/*-----------------------------------------------------------------------------
 * FONT DECLARATIONS
 *---------------------------------------------------------------------------*/
// OXYGEN icon font
LV_FONT_DECLARE(lv_font_oxygen_24);

// TEMP icon font
LV_FONT_DECLARE(lv_font_temp_24);

// AMBIENT icon font
LV_FONT_DECLARE(lv_font_ambient_24);

// IP_ADDRESS icon font
LV_FONT_DECLARE(lv_font_ip_address_24);

// BATTERY icon font
LV_FONT_DECLARE(lv_font_battery_24);

// HEART icon font
LV_FONT_DECLARE(lv_font_heart_24);

// CONFIG icon font
LV_FONT_DECLARE(lv_font_config_24);

// WIFI icon font
LV_FONT_DECLARE(lv_font_wifi_24);

// LUNG icon font
LV_FONT_DECLARE(lv_font_lung_24);

// ECG icon font
LV_FONT_DECLARE(lv_font_ecg_24);

// MONITOR icon font
LV_FONT_DECLARE(lv_font_monitor_24);

/*-----------------------------------------------------------------------------
 * ICON DEFINITIONS (UTF-8 Encoded)
 *---------------------------------------------------------------------------*/
// OXYGEN icon (U+F6DB)
#define ICON_OXYGEN "\xEF\x9B\x9B"

// TEMP icon (U+E1FF)
#define ICON_TEMP "\xEE\x87\xBF"

// AMBIENT icon (U+F6C4)
#define ICON_AMBIENT "\xEF\x9B\x84"

// IP_ADDRESS icon (U+EB2F)
#define ICON_IP_ADDRESS "\xEE\xAC\xAF"

// BATTERY icon (U+E1A4)
#define ICON_BATTERY "\xEE\x86\xA4"

// HEART icon (U+E87D)
#define ICON_HEART "\xEE\xA1\xBD"

// CONFIG icon (U+E8B8)
#define ICON_CONFIG "\xEE\xA2\xB8"

// WIFI icon (U+E63E)
#define ICON_WIFI "\xEE\x98\xBE"

// LUNG icon (U+E127)
#define ICON_LUNG "\xEE\x84\xA7"


// ECG icon (U+F80F)
#define ICON_ECG "\xEF\xA0\x8F"

// MONITOR icon (U+EF5B)
#define ICON_MONITOR "\xEE\xBD\x9B"




























#ifdef __cplusplus
}
#endif

#endif // CUSTOM_ICONS_H
